apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflow-db
  labels:
    app: nextflow-db
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextflow-db
  template:
    metadata:
      labels:
        app: nextflow-db
        chart: {{ template "nextflow-api.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nextflow-db
        image: bentsherman/nextflow-db
        env:
        {{ if .Values.Remote.Enabled }}
        - name: PVC_NAME
          value: {{ .Values.Remote.PVC }}
        {{ else if .Values.NewLocalPVC.Enabled }}
        - name: PVC_NAME
          value: {{ .Values.NewLocalPVC.Name }}
        {{ else if .Values.ExistingLocalPVC.Enabled }}
        - name: PVC_NAME
          value: {{ .Values.ExistingLocalPVC.Name }}
        {{ end }}
        command:
        - /bin/bash
        - -c
        - ./scripts/db-startup.sh; sleep infinity
        resources:
          requests:
            cpu: {{ .Values.Database.Resources.Requests.CPU }}
            memory: {{ .Values.Database.Resources.Requests.Memory }}
          limits:
            cpu: {{ .Values.Database.Resources.Limits.CPU }}
            memory: {{ .Values.Database.Resources.Limits.Memory }}
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        ports:
        - containerPort: 27017
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - ./scripts/db-backup.sh prestop; mongod --shutdown
      volumes:
      {{ if .Values.NewLocalPVC.Enabled }}
      - name: vol-1
        persistentVolumeClaim:
          claimName: {{ .Values.NewLocalPVC.Name }}
      {{ end }}
      {{ if .Values.ExistingLocalPVC.Enabled }}
      - name: vol-1
        persistentVolumeClaim:
          claimName: {{ .Values.ExistingLocalPVC.Name }}
      {{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: nextflow-db
  labels:
    app: nextflow-db
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: nextflow-db
  ports:
  - port: 27017
    targetPort: 27017
