# Default values for nextflow-api.
# Declare variables to be passed into your templates.

# PVC
NewLocalPVC:
  # If true, create new PVC on local cluster.
  Enabled: false
  Name: nextflow-api-pvc
  StorageClass: nfs
  Size: 20Gi

ExistingLocalPVC:
  # If true, use existing PVC on local cluster.
  Enabled: true
  Name: deepgtex-prp

Remote:
  # If true, use PVC/compute of remote cluster.
  # Otherwise, PVC/compute of local cluster will be used.
  # (temp, future will be dynamically configurable)
  Enabled: false
  Context: nautilus
  PVC: deepgtex-prp

# Database deployment settings
Database:
  # Resource requests and limits per container
  Resources:
    Requests:
      CPU: 4
      Memory: 8Gi
    Limits:
      CPU: 8
      Memory: 16Gi

# Web server deployment settings
WebServer:
  # Number of containers
  Replicas: 1
  # Resource requests and limits per container
  Resources:
    Requests:
      CPU: 1
      Memory: 4Gi
    Limits:
      CPU: 1
      Memory: 4Gi

# Ingress control settings
Ingress:
  # If true, use Ingress control.
  # Otherwise, generic LoadBalancer networking will be used,
  # and the other settings in this section will be ignored.
  Enabled: true
  # The subdomain to associate with this service.
  Host: nextflow-api.nautilus.optiputer.net
  # The class of the ingress controller to use.
  # For SLATE this should be 'slate'.
  Class: traefik
